[package]
name = "kona-net"
version = "0.1.1"
description = "Consensus networking library for the OP Stack"

edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
# Alloy
alloy-rlp.workspace = true
alloy-primitives = { workspace = true, features = ["k256", "getrandom"] }
alloy-rpc-types-engine = { workspace = true, features = ["std"] }

# Op Alloy
op-alloy-rpc-types-engine = { workspace = true, features = ["std"] }

# Networking
snap.workspace = true
futures.workspace = true
discv5.workspace = true
libp2p = { workspace = true, features = ["macros", "tokio", "tcp", "noise", "gossipsub", "ping", "yamux"] }
openssl = { workspace = true, features = ["vendored"] }
libp2p-identity = { workspace = true, features = ["secp256k1"] }

# Misc
tokio.workspace = true
tracing.workspace = true
thiserror.workspace = true
lazy_static.workspace = true
unsigned-varint.workspace = true

# `arbitrary` feature dependencies
arbitrary = { workspace = true, features = ["derive"], optional = true }

[dev-dependencies]
arbtest.workspace = true
arbitrary = { workspace = true, features = ["derive"] }
alloy-primitives = { workspace = true, features = ["arbitrary"] }

[features]
default = []
arbitrary = ["dep:arbitrary", "alloy-primitives/arbitrary"]
